### ISSUE TITLE
ftrp export xx 项目无法正常生成

### ISSUE THREAD

**Issue by huoxiangdong** [louis-tru/ftr#10]
![image](https://user-images.githubusercontent.com/18095882/97589098-1d7aa600-1a38-11eb-9623-0d545b57a082.png)
gyp: Unable to find targets in build file demo.gyp
Error: Command failed: 			GYP_GENERATORS=xcode /Users/farmer/Documents/Code/Laboratory/ftr/out/ftrp/gyp/gyp 			-f xcode 	--generator-output="/Users/farmer/Documents/Code/Laboratory/demo/Project/ios" 			-Goutput_dir="out" 			-Gstandalone  -Iout/_var.gypi -I../ftr/out/ftrp/product/ftr.gypi 			demo.gyp 			--depth=. 		
gyp: Unable to find targets in build file demo.gyp
大神，请看看什么情况

**Comment by louis-tru** [comment]
现在应该可以编译了

**Comment by huoxiangdong** [comment]
@louis-tru 

ftrp export ios 
导出项目的时候，还是会报错
```
Run `npm audit` for details.
Error: EPERM: operation not permitted, unlink 'node_modules/examples'
    at Object.unlinkSync (node:fs:1214:3)
    at /Users/farmer/Documents/Code/Laboratory/ftr/out/ftrp/build.js:634:34
    at Array.forEach (<anonymous>)
    at FtrBuild.install_depe (/Users/farmer/Documents/Code/Laboratory/ftr/out/ftrp/build.js:634:18)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async FtrBuild.build (/Users/farmer/Documents/Code/Laboratory/ftr/out/ftrp/build.js:662:20)
    at async FtrExport.export (/Users/farmer/Documents/Code/Laboratory/ftr/out/ftrp/export.js:712:17) {
  errno: -1,
  syscall: 'unlink',
  code: 'EPERM',
  path: 'node_modules/examples'
}
```

**Comment by huoxiangdong** [comment]
@louis-tru 
ftrp export ios 依然失败
```
gyp: Unable to find targets in build file demo.gyp
Error: Command failed: 			GYP_GENERATORS=xcode /Users/farmer/Documents/Code/Laboratory/ftr/out/ftrp/gyp/gyp 			-f xcode 			--generator-output="/Users/farmer/Documents/Code/Laboratory/demo/Project/ios" 			-Goutput_dir="out" 			-Gstandalone  -Iout/_var.gypi -I../ftr/out/ftrp/product/ftr.gypi 			demo.gyp 			--depth=. 		
gyp: Unable to find targets in build file demo.gyp

    at checkExecSyncError (node:child_process:636:11)
    at Object.execSync (node:child_process:672:15)
    at FtrExport.gen_project_file (/Users/farmer/Documents/Code/Laboratory/ftr/out/ftrp/export.js:517:33)
    at FtrExport.export_result (/Users/farmer/Documents/Code/Laboratory/ftr/out/ftrp/export.js:555:24)
    at FtrExport.export (/Users/farmer/Documents/Code/Laboratory/ftr/out/ftrp/export.js:733:18)
    at processTicksAndRejections (node:internal/process/task_queues:93:5) {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 67 79 70 3a 20 55 6e 61 62 6c 65 20 74 6f 20 66 69 6e 64 20 74 61 72 67 65 74 73 20 69 6e 20 62 75 69 6c 64 20 66 69 6c 65 20 64 65 6d 6f 2e 67 79 70 ... 1 more byte>
  ],
  pid: 26978,
  stdout: <Buffer >,
  stderr: <Buffer 67 79 70 3a 20 55 6e 61 62 6c 65 20 74 6f 20 66 69 6e 64 20 74 61 72 67 65 74 73 20 69 6e 20 62 75 69 6c 64 20 66 69 6c 65 20 64 65 6d 6f 2e 67 79 70 ... 1 more byte>
}
```

**Comment by huoxiangdong** [comment]
ftrp export android 也不行
```
Error: ENOENT: no such file or directory, open '/Users/farmer/Documents/Code/Laboratory/demo/Project/android/gradle.properties'
    at Object.openSync (node:fs:476:3)
    at Object.readFileSync (node:fs:377:35)
    at FtrExport.export_result_android (/Users/farmer/Documents/Code/Laboratory/ftr/out/ftrp/export.js:662:18)
    at FtrExport.export (/Users/farmer/Documents/Code/Laboratory/ftr/out/ftrp/export.js:730:18)
    at processTicksAndRejections (node:internal/process/task_queues:93:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/farmer/Documents/Code/Laboratory/demo/Project/android/gradle.properties'
}
```

**Comment by louis-tru** [comment]
> @louis-tru
> 
> ```
> Run `npm audit` for details.
> Error: EPERM: operation not permitted, unlink 'node_modules/examples'
>     at Object.unlinkSync (node:fs:1214:3)
>     at /Users/farmer/Documents/Code/Laboratory/ftr/out/ftrp/build.js:634:34
>     at Array.forEach (<anonymous>)
>     at FtrBuild.install_depe (/Users/farmer/Documents/Code/Laboratory/ftr/out/ftrp/build.js:634:18)
>     at processTicksAndRejections (node:internal/process/task_queues:93:5)
>     at async FtrBuild.build (/Users/farmer/Documents/Code/Laboratory/ftr/out/ftrp/build.js:662:20)
>     at async FtrExport.export (/Users/farmer/Documents/Code/Laboratory/ftr/out/ftrp/export.js:712:17) {
>   errno: -1,
>   syscall: 'unlink',
>   code: 'EPERM',
>   path: 'node_modules/examples'
> }
> ```
> 
> 编译的ftrp命令还是有问题
> 
> 1. unlink错误，我先注释掉
> 2. 遍历到 ./bin下寻找pacage.json err 我先过滤掉./文件夹
>    好了，命令可以使用了，但是 export 项目依然报错
> 
> ftrp export ios
> 导出项目的时候，还是会报错

编译工程源码是不会执行到ftrp中去的，编译只是c++与拷贝一些文件，你确定这是编译时产生的？

**Comment by louis-tru** [comment]
或者你可以通过 npm install ftrp -g 试试这个，这是我编译好的工具链

**Comment by huoxiangdong** [comment]
目前我遇到的问题:
1. npm i ftrp -g 问题一样
2. 不加点的话,会安装远程依赖，而不是本地,unlink err也是这个问题造成的
![image](https://user-images.githubusercontent.com/18095882/97741927-7fadd680-1b1e-11eb-9f63-9d982f3a609c.png)
3. 需要加入somes依赖，test.ts编译的时候需要
![image](https://user-images.githubusercontent.com/18095882/97742114-d1566100-1b1e-11eb-8869-955b0213a8ce.png)
4.默认会寻找./bin/pacage.json, 报错，所以过滤掉了./bin,
![image](https://user-images.githubusercontent.com/18095882/97742436-3f9b2380-1b1f-11eb-88fb-d09937d357b7.png)
5. tsc需要只定 3.97，不要会编译错误
6.ftrp export ios 报Unable to find targets in build file demo.gyp 没有解决，因为我对gyp不熟悉

**Comment by huoxiangdong** [comment]
@louis-tru 
目前我遇到的问题
1. 需要加./ 不然默认会添加远程依赖，而不是本地 , unlink err 也是这个原因造成的
```
for (var key in proj) {
            if (key == '@apps') {
                for (var name in proj['@apps']) {
									apps.push( './' + name);
                }
            }
        }
```
2. tsc需要指定版本，不然会编译失败
3. 需要添加somes依赖，因为test.ts 引入了somes，编译的时候报错
```
var json = {
                    name: project_name,
                    app: project_name,
                    id: `org.ftr.${project_name}`,
                    main: 'index.js',
                    types: 'index.d.ts',
										version: '1.0.0',
										dependencies: {
											somes: "~0.10.112",
										}
                 };
```
4. 过滤掉了./bin，因为默认会寻找 ./bin/pacages.json，没有会报错
```
fs.listSync(node_modules, function (stat, pathname) {
                            if (pathname && stat.isDirectory() && !/^\./.test(stat.name))
                                host.solve(node_modules + '/' + stat.name, false, true);
                        });
```

**Comment by huoxiangdong** [comment]
@louis-tru 
经过以上处理，android项目可以导出了，但是运行黑屏，一会儿就闪退了

**Comment by huoxiangdong** [comment]
@louis-tru 
ios端 err
```
/Users/farmer/Documents/Code/Laboratory/demo_1/Project/ios/demo_1.xcodeproj The linked and embedded framework 'ftr.framework' is missing one or more architectures required by this target: arm64.
```

**Comment by huoxiangdong** [comment]
@louis-tru 
ftrp命令相关的错误，更多的原因是 node、typescript版本造成的，分别降低版本，解决了大部分问题
