### ISSUE TITLE
导出的android demo 运行黑屏

### ISSUE THREAD

**Issue by huoxiangdong** [louis-tru/ftr#11]
就这样一直黑着，然后过了一会儿就自动退出了
![image](https://user-images.githubusercontent.com/18095882/97780073-5a23da00-1bbd-11eb-8d3d-ea4e3ee40685.png)

**Comment by huoxiangdong** [comment]
导出ios项目也无法运行
err: is missing one or more architectures required by this target: arm64.
![image](https://user-images.githubusercontent.com/18095882/97780895-84c46180-1bc2-11eb-9ada-3913cda71d46.png)

**Comment by huoxiangdong** [comment]
是否可以上传一个example demo, 不知道问题出在哪里

**Comment by louis-tru** [comment]
> 就这样一直黑着，然后过了一会儿就自动退出了
> ![image](https://user-images.githubusercontent.com/18095882/97780073-5a23da00-1bbd-11eb-8d3d-ea4e3ee40685.png)

android的问题还有待调试

**Comment by louis-tru** [comment]
> 导出ios项目也无法运行
> err: is missing one or more architectures required by this target: arm64.
> ![image](https://user-images.githubusercontent.com/18095882/97780895-84c46180-1bc2-11eb-9ada-3913cda71d46.png)

最新的代码应该没有这个问题了

**Comment by louis-tru** [comment]
我这周花些时间解决下这些问题
