### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by huoxiangdong** [louis-tru/ftr#12]
ftrp export ios 导出项目运行闪退
err
```
Error: Cannot find module 'http://192.168.31.88:1026/demo_8/'
    at throw_MODULE_NOT_FOUND (_pkg:103:15)
    at PackageIMPL.resolveRelative (_pkg:891:9)
    at resolveFilename (_pkg:538:30)
    at Function._load (_pkg:362:42)
    at startup (_pkg:413:24)
    at <anonymous>
```
![image](https://user-images.githubusercontent.com/18095882/97796397-73c03280-1c4c-11eb-8992-f2a3ebc02401.png)

**Comment by louis-tru** [comment]
找不到module的问题还没解决，这个应该是内部的js bug

**Comment by louis-tru** [comment]
ios 找不到模块问题已经修复，但在开发环境时不能从网络启动，因为现在runtime不能解析ts代码， 这个在之前的代码中是可以的，但后来考虑到代码的复杂性删除了此功能。
现在需要在ftrp启动调试http服务时把ts文件实时转换成js文件。
<img width="808" alt="WechatIMG7" src="https://user-images.githubusercontent.com/1221969/98440553-6adfcd00-2134-11eb-8589-35e66a603111.png">

**Comment by huoxiangdong** [comment]
@louis-tru 
运行后报
```
TypeError: Cannot set property Action of #<Object> which has only a getter
    at Function.assign (<anonymous>)
    at Object.<anonymous> (ext://ftr/action.js:18:8)
    at Module._compile (_pkg.js:305:42)
    at Object..js (_pkg.js:513:16)
    at Module.load (_pkg.js:268:38)
    at tryModuleLoad (_pkg.js:527:16)
    at Function._load (_pkg.js:377:9)
    at Module.require (_pkg.js:274:23)
    at require (_pkgutil.js:238:20)
    at Object.<anonymous> (ext://ftr/index.js:22:16)

```
![image](https://user-images.githubusercontent.com/18095882/98447692-e0ae5d80-2161-11eb-9676-91ec01b3b7d7.png)

**Comment by huoxiangdong** [comment]
@louis-tru 
临时解决了一下，具体原因我不知道
```
exports.Action = {...exports.Action, ..._action}
```
![image](https://user-images.githubusercontent.com/18095882/98448216-6d0e4f80-2165-11eb-93cc-e1e986e9a354.png)

**Comment by huoxiangdong** [comment]
@louis-tru 
android也可打开了，但是demo里访问Http、File System就闪退
```
2020-11-08 02:13:34.144 9197-9197/org.ftr.examples D/Ftr: ACTION_BATTERY_CHANGED
2020-11-08 02:13:39.590 9197-9212/org.ftr.examples A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 9212 (Thread-2)
```
![image](https://user-images.githubusercontent.com/18095882/98448588-09d1ec80-2168-11eb-836e-07ad70e27686.png)

**Comment by huoxiangdong** [comment]
ios也是
![image](https://user-images.githubusercontent.com/18095882/98456701-d6b94880-21bb-11eb-900e-2a35780de71e.png)

**Comment by louis-tru** [comment]
> @louis-tru
> android也可打开了，但是demo里访问Http、File System就闪退
> 
> ```
> 2020-11-08 02:13:34.144 9197-9197/org.ftr.examples D/Ftr: ACTION_BATTERY_CHANGED
> 2020-11-08 02:13:39.590 9197-9212/org.ftr.examples A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 9212 (Thread-2)
> ```
> 
> ![image](https://user-images.githubusercontent.com/18095882/98448588-09d1ec80-2168-11eb-836e-07ad70e27686.png)

是从网络启动，不是启动后访问文件系统？

**Comment by louis-tru** [comment]
> @louis-tru
> android也可打开了，但是demo里访问Http、File System就闪退
> 
> ```
> 2020-11-08 02:13:34.144 9197-9197/org.ftr.examples D/Ftr: ACTION_BATTERY_CHANGED
> 2020-11-08 02:13:39.590 9197-9212/org.ftr.examples A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 9212 (Thread-2)
> ```
> 
> ![image](https://user-images.githubusercontent.com/18095882/98448588-09d1ec80-2168-11eb-836e-07ad70e27686.png)

是从网络启动？还是启动后访问文件系统？

**Comment by huoxiangdong** [comment]
> > @louis-tru
> > android也可打开了，但是demo里访问Http、File System就闪退
> > ```
> > 2020-11-08 02:13:34.144 9197-9197/org.ftr.examples D/Ftr: ACTION_BATTERY_CHANGED
> > 2020-11-08 02:13:39.590 9197-9212/org.ftr.examples A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 9212 (Thread-2)
> > ```
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/18095882/98448588-09d1ec80-2168-11eb-836e-07ad70e27686.png)
> 
> 是从网络启动？还是启动后访问文件系统？
网络、本地都是这样

**Comment by louis-tru** [comment]
访问io现在已经修复了，在master或v0.x分支上。你那边可以在android上运行吗？我这没有办法运行起来，可能是因为我的ndk版本比较高。

**Comment by huoxiangdong** [comment]
@louis-tru 
嗯，现在可以了，我的android的可以运行，现在ios、android都可以跑起来了。
今天，才发现，您写的touch code，我手机好久就下载了，一直没用，好像也好久没更新了
看了下，和现在比较火的jsbox、play.js 差不多，这两款也是加入了nodejs，他们的ui只是不是自绘的而已
用ftr应该能写个nodejs版的pythonista，嗯，优秀！
