### ISSUE TITLE
Error: Event listener function type is incorrect

### ISSUE THREAD

**Issue by huoxiangdong** [louis-tru/ftr#13]
![image](https://user-images.githubusercontent.com/18095882/98512262-02fac500-22a1-11eb-9c6a-7b5afe53287a.png)
是不是因为这个
```
	onClick="m_handle_click"
```
![image](https://user-images.githubusercontent.com/18095882/98512474-540ab900-22a1-11eb-8622-506e6bed0dfd.png)

**Comment by huoxiangdong** [comment]
嗯，是这个原因，修改了下可以了
![image](https://user-images.githubusercontent.com/18095882/98514544-9255a780-22a4-11eb-832c-7e77785e6c00.png)

**Comment by louis-tru** [comment]
已经解决了，确实是这个问题。最早js版本是可以使用字符串做为处理器，但后来换成ts后删除了对字符串支持，但有些地方没有改到位
