### ISSUE TITLE
编译报错误 error: no member named 'VIEW' in 'ftr::View'

### ISSUE THREAD

**Issue by huoxiangdong** [louis-tru/ftr#9]
../../ftr-js/js.cc:514:53: error: no member named 'VIEW' in 'ftr::View'
        return m_inl->m_classs->instanceof(val, ftr::View::VIEW);

请教下，啥问题

**Comment by louis-tru** [comment]
ftrp 命令没有上传到npm，需要自己编译。
之前编译有问题，现在应该可以了

**Comment by louis-tru** [comment]
最近忙着做别的事情，这个项目也是心头的痛，一直想做一个大更新，但没时间弄

**Comment by huoxiangdong** [comment]
我很喜欢这个项目，支持大神
